### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [XiaoMi/pegasus-java-client#111]
https://github.com/XiaoMi/pegasus-java-client/blob/33a9a05f1929293275a1952dbd4457923f83e1f9/src/main/java/com/xiaomi/infra/pegasus/client/PegasusClient.java#L56-L68

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.
Declare a volatile local variable table offers a much more elegant solution

**Comment by totalo** [comment]
I think it is not necessary to declare volatile for local variables.

**Comment by Shuo-Jia** [comment]
`Double-Checked Locking may not work` is right, which usually may because the `new Table` actually isn't `atomic` operation and the step of `construct` may be `re-order` under compiler optimization, so that the `table != null` but may not be `complete object`(for example, it's field may have not be inited base user setting). So `volatile` can forbid the `re-order` and is used for resolving the case widely. 

If my understand is right, and then: 
* Firstly,  `volatile` can't be allowed to be used as `local variable`, so I think the solution isn‘t appropriate if the code was wrong.
* Secondly, `table` is local variable, every thread will create own copy variable, and put the `ConcurrentHashMap` **after** the `table` is complete inited, So it shouldn't happen the case: put one `incomplete` table object into `ConcurrentHashMap` and obtain by another thread. 

So the code shoud be right and no need fix as above explain. However, if you have other reason or case which may be result in unexpected result, welcome to continue discuss.
